// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR9KpZt_akmct-whgI5RukTsJNCY3K9j4',
    appId: '1:1000011397879:web:4b110c30fe8820a2def1f2',
    messagingSenderId: '1000011397879',
    projectId: 'scanventory-c9ea2',
    authDomain: 'scanventory-c9ea2.firebaseapp.com',
    storageBucket: 'scanventory-c9ea2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEKJ2MKZj6GBQ-_RsK8Wlo2AlttFMWp48',
    appId: '1:1000011397879:android:fbed355f29d021cadef1f2',
    messagingSenderId: '1000011397879',
    projectId: 'scanventory-c9ea2',
    storageBucket: 'scanventory-c9ea2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGiErVIwR5cOh882VDbbQoGtL2odX89g0',
    appId: '1:1000011397879:ios:847c8f3f91cfbc32def1f2',
    messagingSenderId: '1000011397879',
    projectId: 'scanventory-c9ea2',
    storageBucket: 'scanventory-c9ea2.firebasestorage.app',
    iosBundleId: 'com.asnproject.scanventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGiErVIwR5cOh882VDbbQoGtL2odX89g0',
    appId: '1:1000011397879:ios:847c8f3f91cfbc32def1f2',
    messagingSenderId: '1000011397879',
    projectId: 'scanventory-c9ea2',
    storageBucket: 'scanventory-c9ea2.firebasestorage.app',
    iosBundleId: 'com.asnproject.scanventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR9KpZt_akmct-whgI5RukTsJNCY3K9j4',
    appId: '1:1000011397879:web:0cdb2f9809a43338def1f2',
    messagingSenderId: '1000011397879',
    projectId: 'scanventory-c9ea2',
    authDomain: 'scanventory-c9ea2.firebaseapp.com',
    storageBucket: 'scanventory-c9ea2.firebasestorage.app',
  );
}
